---

- name: Download golang
  get_url:
    url: "https://golang.org/dl/go{{ golang_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ golang_version }}.linux-amd64.tar.gz"
  register: download

- name: Register the current golang version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: true
  register: current_golang_version
  changed_when: false

- name: Remove old golang files
  become: true
  file:
    path: "/usr/local/go"
    state: absent
  when: current_golang_version.failed or current_golang_version.stdout != golang_version_target

- name: Extract and install golang
  become: true
  unarchive:
    src: "/tmp/go{{ golang_version }}.linux-amd64.tar.gz"
    dest: "/usr/local/"
    copy: no
  when: current_golang_version.failed or current_golang_version.stdout != golang_version_target
