---

- name: Register the current helm version (if any)
  ansible.builtin.command: /usr/local/bin/helm version --short
  ignore_errors: true
  register: current_helm_version
  changed_when: false

- name: Download helm
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "/tmp/helm-v{{ helm_version }}-linux-amd64.tar.gz"
  when: current_helm_version.failed or not current_helm_version.stdout is search(helm_version)

- name: Remove old helm files
  become: true
  ansible.builtin.file:
    path: "/usr/local/bin/helm"
    state: absent
  when: current_helm_version.failed or not current_helm_version.stdout is search(helm_version)

- name: Extract helm
  ansible.builtin.unarchive:
    src: "/tmp/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "/tmp"
    copy: no
  when: current_helm_version.failed or not current_helm_version.stdout is search(helm_version)

- name: Install helm
  become: true
  ansible.builtin.copy:
    remote_src: true
    src:  "/tmp/linux-amd64/helm"
    dest: "/usr/local/bin/helm"
    mode: "0755"
  when: current_helm_version.failed or not current_helm_version.stdout is search(helm_version)
