---

- name: Install default packages
  become: true
  apt:
    state: present
    update_cache: yes
    pkg:
      - git
      - git-lfs
      - ssh
      - iftop
      - make
      - unzip
      - tree
      - ranger
      - vim

- name: Rollout .profile
  ansible.builtin.copy:
    src: "{{ role_path }}/files/.profile"
    dest: "~/.profile"

- name: Rollout .bashrc
  ansible.builtin.copy:
    src: "{{ role_path }}/files/.bashrc"
    dest: "~/.bashrc"

- name: Rollout .bash_aliases
  ansible.builtin.copy:
    src: "{{ role_path }}/files/.bash_aliases"
    dest: "~/.bash_aliases"

- name: Rollout .gitconfig
  ansible.builtin.copy:
    src: "{{ role_path }}/files/.gitconfig"
    dest: "~/.gitconfig"
